Config:
  # The plugin will send an update notification message when it finds an available update.
  update_notification: true
  # When the timer ends, how many ticks should wait to hide the boss bar (1 second = 20 ticks)
  ticks_hide_after_ending: 60
  # Which text formatter to use (MINIMESSAGE, LEGACY or UNIVERSAL)
  # Please note that UNIVERSAL requires the most resources, but supports all types of formats.

  # (&x&f&f&5&5&f&fc and &#ff55ff LEGACY - <color:#ff55ff> MINIMESSAGE)
  text_format: LEGACY
  # How many ticks should the boss bar text refresh?
  # It is usually used when you use animations to make them more fluid.
  refresh_ticks: 10
  # Should the plugin save and load the timer states when the server is closed and opened?
  save_state_timers: true

Messages:
  commandReload: '&aConfig Reloaded.'
  commandNoPermissions: '&cYou don''t have permissions to use this command.'
  timerSetError: '&cUse: /vct set <HH:MM:SS>'
  timerSetFormatIncorrect: '&cIncorrect format. Please use HH:MM:SS'
  timerSetFormatInvalid: '&cThe format does not contain a valid number.'
  timerSetFormatOutRange: '&cThe timer must be greater than 0 seconds.'
  timerModifyInvalid: '&cUse: /vct modify <modifier>'
  timerModifyAddError: '&cUse: /vct modify add <HH:MM:SS>'
  timerModifyAdd: '&a%HH%:%MM%:%SS% has been added to the timer.'
  timerModifySetError: '&cUse: /vct modify set <HH:MM:SS>'
  timerModifySet: '&aThe timer was set to %HH%:%MM%:%SS%.'
  timerModifyTakeError: '&cUse: /vct modify take <HH:MM:SS>'
  timerModifyTake: '&a%HH%:%MM%:%SS% has been removed from the timer.'
  timerModifyBarcolorError: '&cUse: /vct modify barcolor <color>. &eYou can use these colors: BLUE, GREEN, PINK, PURPLE, RED, WHITE, or YELLOW.'
  timerModifyBarcolorInvalid: '&cThe color "%COLOR%" of the timer boss bar is invalid. Use BLUE, GREEN, PINK, PURPLE, RED, WHITE, or YELLOW.'
  timerModifyBarcolor: '&aThe color of the timer %TIMER% has been changed to "%COLOR%".'
  timerModifySoundError: '&cUse: /vct modify sound <"sound in quotes">'
  timerModifySoundRequireQuotes: '&cThe sound needs to be enclosed in quotation marks (") in order to change it.'
  timerModifySound: '&aThe sound of the timer %TIMER% has been changed to "%SOUND%" &e(%TYPE%)&a.'
  timerModifySoundenableError: '&cUse: /vct modify sound_enable <true|false>'
  timerModifySoundenableInvalid: '&cThe boolean is invalid. Use TRUE or FALSE.'
  timerModifySoundenable: '&aThe sound_enable of the timer %TIMER% has been changed to %SOUNDENABLE%.'
  timerModifySoundvolumeError: '&cUse: /vct modify sound_volume <0.1 - 2.0>'
  timerModifySoundvolumeInvalid: '&cThe number is invalid. Please use a number between &e0.1 &cand &e2.0.'
  timerModifySoundvolumeOutRange: '&cThe volume must be between &e0.1 &cand &e2.0&c.'
  timerModifySoundvolume: '&aThe sound_volume of the timer %TIMER% has been changed to &e%VOLUME%&a.'
  timerModifySoundpitchError: '&cUse: /vct modify sound_pitch <0.1 - 2.0>'
  timerModifySoundpitchInvalid: '&cThe number is invalid. Please use a number between &e0.1 &cand &e2.0.'
  timerModifySoundpitchOutRange: '&cThe pitch must be between &e0.1 &cand &e2.0&c.'
  timerModifySoundpitch: '&aThe sound_pitch of the timer %TIMER% has been changed to &e%PITCH%&a.'
  timerModifyTextError: '&cUse: /vct modify text <"text in quotes">'
  timerModifyTextRequireQuotes: '&cThe text needs to be enclosed in quotation marks (") in order to change it.'
  timerModifyText: '&aThe text of the timer %TIMER% has been changed to "&r%TEXT%&a".'
  timerStart: '&aTimer started of %HH%:%MM%:%SS%!'
  timerPause: '&6Timer paused!'
  timerResume: '&6Timer resumed!'
  timerStop: '&6Timer stopped!'
  timerDontExists: '&cThe timer does not exist.'
  timerConfigNotFound: '&cThe timer configuration could not be found.'

Timers:
  default:
    text: "%HH%:%MM%:%SS%" # The text of the boss bar (%HH% hours, %MM% minutes, %SS% seconds)
    sound: UI_BUTTON_CLICK # The sound of the timer every second
    sound_volume: 1.0 # The volume of the sound (1.0 is 100%)
    sound_pitch: 1.0 # The pitch of the sound (1.0 is normal pitch)
    bossbar_color: WHITE # The boss bar color is BLUE, GREEN, PINK, PURPLE, RED, WHITE, or YELLOW.
    enabled: true # Defines whether this timer is available for selection.
    sound_enabled: false # Defines whether this timer plays sound every second.

  timer_1:
    text: "&aI'm the Timer 1 :D (%HH%:%MM%:%SS%)" # The text of the boss bar (%HH% hours, %MM% minutes, %SS% seconds)
    sound: UI_BUTTON_CLICK # The sound of the timer every second
    sound_volume: 0.5 # The volume of the sound (1.0 is 100%)
    sound_pitch: 2.0 # The pitch of the sound (1.0 is normal pitch)
    bossbar_color: GREEN # The boss bar color is BLUE, GREEN, PINK, PURPLE, RED, WHITE, or YELLOW.
    enabled: true # Defines whether this timer is available for selection.
    sound_enabled: true # Defines whether this timer plays sound every second.